### ISSUE TITLE
Setup 3.0 login broken

### ISSUE THREAD

**Issue by kitsunet** [neos/setup#39]
The setup login is not adapted to new POST arguments and won't work currently.

**Comment by putheakhem** [comment]
i have the same problem !

**Comment by gerhard-boden** [comment]
Until it's fixed you can do the following: Manually edit the `Configuration/Settings.yaml`, run `./flow doctrine:migrate` add a new user via CLI `./flow user:create` import your site package via `./flow site:import`

**Comment by putheakhem** [comment]
@gerhard-boden  can you give me example of `user:create`

**Comment by aertmann** [comment]
Fixed with https://github.com/neos/setup/commit/60514232f72adac15b89344e164e05630027825b

**Comment by aertmann** [comment]
Broken due to https://github.com/neos/flow-development-collection/pull/838
